// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/project-overview/Architecture.tsx": () => import("../components/mockups/project-overview/Architecture.tsx")
};
